config/routes.rb
Rails.application.routes.draw do
  resources :to_dos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: %i[ show edit update destroy ]

  # GET /to_dos or /to_dos.json
  def index
    @to_dos = ToDo.all
    @to_do = ToDo.new
  end

  # GET /to_dos/1 or /to_dos/1.json
  def show
  end

  # GET /to_dos/new
  def new
    @to_do = ToDo.new
  end

  # GET /to_dos/1/edit
  def edit
  end

  # POST /to_dos or /to_dos.json
  def create
    @to_do = ToDo.new(to_do_params)

    if @to_do.save
      render turbo_stream: turbo_stream.append(:todo_index, partial: "to_do", locals: { to_do: @to_do })
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /to_dos/1 or /to_dos/1.json
  def update
    respond_to do |format|
      if @to_do.update(to_do_params)
        format.html { redirect_to to_do_url(@to_do), notice: "To do was successfully updated." }
        format.json { render :show, status: :ok, location: @to_do }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1 or /to_dos/1.json
  def destroy
    @to_do.destroy

    respond_to do |format|
      format.html { redirect_to to_dos_url, notice: "To do was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do
      @to_do = ToDo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def to_do_params
      params.require(:to_do).permit(:title, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7Form</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_dos/_form.html.erb
<%= form_with(model: to_do, data: { 'turbo-frame': 'todo_index' }) do |form| %>
  <% if to_do.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
        <% to_do.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :memo, style: "display: block" %>
    <%= form.text_area :memo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/to_dos/_to_do.html.erb
<div id="<%= dom_id to_do %>">
  <p>
    <strong>Title:</strong>
    <%= to_do.title %>
  </p>

  <p>
    <strong>Memo:</strong>
    <%= to_do.memo %>
  </p>

</div>

app/views/to_dos/edit.html.erb
<h1>Editing to do</h1>

<%= render "form", to_do: @to_do %>

<br>

<div>
  <%= link_to "Show this to do", @to_do %> |
  <%= link_to "Back to to dos", to_dos_path %>
</div>

app/views/to_dos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>To dos</h1>

<div id="to_dos">
  <%= turbo_frame_tag 'todo_index' do %>
    <% @to_dos.each do |to_do| %>
      <%= render to_do %>
      <p>
        <%= link_to "Show this to do", to_do %>
      </p>
    <% end %>
  <% end %>
</div>

<%= render "form", to_do: @to_do %>

app/views/to_dos/new.html.erb
<h1>New to do</h1>

<%= render "form", to_do: @to_do %>

<br>

<div>
  <%= link_to "Back to to dos", to_dos_path %>
</div>

app/views/to_dos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @to_do %>

<div>
  <%= link_to "Edit this to do", edit_to_do_path(@to_do) %> |
  <%= link_to "Back to to dos", to_dos_path %>

  <%= button_to "Destroy this to do", @to_do, method: :delete %>
</div>